baseURL = "https://bradfuller.xyz/"
languageCode = "en-AU"
defaultContentLanguage = "en"

title = "Bradley Fuller"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Bradley Fuller"
  headline = "Software Engineer @ One Model Inc"
  image = "img/chiitan.avif"  # path relative to static directory

  links = [
    { email = "mailto:hello@bradfuller.xyz" },
    { linkedin = "https://linkedin.com/in/bradfuller1" },
    { github = "https://github.com/bradf_99" },
    { medium = "https://medium.com/@bradfuller" },
    { stack-overflow = "https://stackoverflow.com/users/11358164/brad-f" },
    { instagram = "https://instagram.com/bradf_99" },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
